fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: petras.jodkonis@gmail.com
    sender_name: 'Petras shows.botai.eu'
  resetting:
    email:
      template: email/password_resetting.email.twig
  registration:
    confirmation:
      enabled: true
      template: '@FOSUser/Registration/email.txt.twig'
