<?php

namespace App\Repository;

use App\Entity\UserShows;
use Doctrine\ORM\EntityRepository;

/**
 * ItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserShowsRepository extends EntityRepository
{
    /**
     * @param $userID
     * @param string $status
     * @return array
     */
    public function getShows($userID, $status = UserShows::STATUS_WATCHING)
    {
        $selected = [];

        if ($status == UserShows::STATUS_WATCHING) {
            $ignore = [UserShows::STATUS_ARCHIVED, UserShows::STATUS_WATCH_LATER];
            $result = $this->createQueryBuilder('p')
                ->where('p.userID = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('p.status is NULL')
                ->orWhere('p.status NOT IN (:status)')
                ->setParameter('status', array_values($ignore))
                ->select('p.showID as id')
                ->getQuery()
                ->getResult();
        } elseif ($status == UserShows::STATUS_ARCHIVED) {
            $result = $this->createQueryBuilder('p')
                ->where('p.userID = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('p.status = :status')
                ->setParameter('status', UserShows::STATUS_ARCHIVED)
                ->select('p.showID as id')
                ->getQuery()
                ->getResult();
        } elseif ($status == UserShows::STATUS_WATCH_LATER) {
            $result = $this->createQueryBuilder('p')
                ->where('p.userID = :userID')
                ->setParameter('userID', $userID)
                ->andWhere('p.status = :status')
                ->setParameter('status', UserShows::STATUS_WATCH_LATER)
                ->select('p.showID as id')
                ->getQuery()
                ->getResult();
        } else {
            $result = $this->createQueryBuilder('p')
                ->where('p.userID = :userID')
                ->setParameter('userID', $userID)
                ->select('p.showID as id')
                ->getQuery()
                ->getResult();
        }

        foreach ($result as $show) {
            $selected[] = $show['id'];
        }
        return $selected;
    }

    /**
     * @return array
     */
    public function getAllUsersShows()
    {
        $selected = [];
        $result = $this->createQueryBuilder('p')
            ->select('p.showID as id')
            ->groupBy('id')
            ->getQuery()
            ->getResult();
        foreach ($result as $show) {
            $selected[] = $show['id'];
        }
        return $selected;
    }
}
